### ISSUE TITLE
Integrasjonstestsystem for Fhi.HelseId

### ISSUE THREAD

**Issue by OsirisTerje** [FHIDev/fhi.helseid#398]
Testdekningen er for lav på Fhi.HelseId.
Mye av koden går på interaksjon med STS, og det krever at man setter opp et STS mocking system for å gjøre slike integrasjonstester.

Det er flere alternativer for dette.
- Mocking tjeneste, ekstern eller intern
- Test instans av IdentityServer

Dette må vurderes.

**Comment by atomfinger** [comment]
Kaster ut mine 2 cents her som kan tas opp i diskusjon:

Det kommer litt an på hva vi ønsker å teste. 

Skal vi teste faktisk integrasjon med andre systemer så mener jeg at man må treffe noe ekte og ikke en mocket tjeneste. Bruker STS en standard, I.e. OAuth 2, eller noe i den dur slik at vi teknisk sett kan dytte inn et annet OAuth2 system via TestContainers? Da ville vi sluppet å ha en egen instanse som hostes noe sted. Kan hende det ikke er mulig, men kanskje verdt å utforske?

Ønsker vi å teste intern logikk i Fhi.HelseId, så er mocking helt innafor imho. Om man da føler at man må ha noe å kalle mot så kan da wiremock.net være et alternativ, ala slik det er gjort her: https://github.com/FHIDev/Fhi.Grunndata.Personoppslag.Api/pull/28.
