### ISSUE TITLE
Anvende innebygd Hpr aksess kontroll

### ISSUE THREAD

**Issue by OsirisTerje** [FHIDev/Fhi.HelseId#399]
I dag anvender vi en egen soap connection til Hpr registeret, med støtte av funksjoner i fhi.helseid.  Dette krever at brukeren må legge inn Hpr login og passord i egen config.

For en stund siden ble dette implementert i helseId STS, og vi bør endre til å ta i bruk dette, det forenkler oppsettet.

Dette gjelder da KUN tilgansghåndtering, ikke at vi kan hente ut mer informasjon fra Hpr registeret, 
Se #38 
og #76 for dette

**Comment by GeirMG** [comment]
Solved by https://github.com/FHIDev/Fhi.HelseId/pull/530
