### ISSUE TITLE
Implementere PAR

### ISSUE THREAD

**Issue by OsirisTerje** [FHIDev/fhi.helseid#435]
Implementasjon ref #364 

[OAuth 2.0 Pushed Authorization Requests](https://datatracker.ietf.org/doc/html/rfc9126)

Steps for OAuth PAR Implementation

1. Client Requests Authorization Request Endpoint: The client sends a request to the authorization server's /par endpoint with the necessary authorization request parameters.

2. Authorization Server Issues PAR Identifier: The authorization server responds with a par parameter (identifier) that the client will use in the subsequent authorization request.

3. Client Makes Authorization Request: The client includes the PAR parameter in the authorization request sent to the /authorize endpoint of the authorization server.

4. Authorization Server Processes Request: The authorization server looks up the parameters associated with the PAR value and processes the authorization request accordingly.

Se https://utviklerportal.nhn.no/informasjonstjenester/helseid/bruksmoenstre-og-eksempelkode/bruk-av-helseid/docs/teknisk-referanse/endepunkt/par-endepunktet_no_nbmd/

**Comment by martinmine** [comment]
PAR is a feature that will come with .NET 9, so we might get this feature for free if we wait until November: 
https://github.com/dotnet/AspNetCore.Docs/issues/33031#issuecomment-2274440169
