### ISSUE TITLE
Oppdatere .NET NuGet pakkene

### ISSUE THREAD

**Issue by yne-bv** [FHIDev/fhi.helseid#474]
Det har kommet nye versjoner av .NET med sikkerhets-patching for dotnet 8 og 6
https://devblogs.microsoft.com/dotnet/dotnet-and-dotnet-framework-october-2024-servicing-updates/#security-improvements

- [x] Oppdater .NET 6 til 6.0.35 
- [x] Oppdater .NET 8 til .NET 8.0.10
- [x] Oppdater .NET 9 til RC2

**Comment by GeirMG** [comment]
Dette er løst: https://github.com/FHIDev/fhi.helseid/pull/500
