### ISSUE TITLE
Mismatch i testdata mellom HelseId og Hpr?

### ISSUE THREAD

**Issue by GeirMG** [FHIDev/Fhi.HelseId#483]
Helseid bruker testdata fra Persontjenesten.
Hva bruker Hpr-registeret?

Hvis Hpr-registeret bruker PREG har vi ett issue.

**Comment by GeirMG** [comment]
HelseId bruker ikke lengre Hpr-registeret. Dette ble endret med: https://github.com/FHIDev/Fhi.HelseId/pull/530

Nå hentes HPR-data fra /userinfo-endepunktet, og bruker og HPR-informasjon er derfor i sync.

Denne saken kan derfor muligens lukkes?

**Comment by yne-bv** [comment]
Vi har skrevet oss bort fra å slå opp HPR fra APIet.
Vi får nå denne informasjonen fra STS-en.
Derfor er ikke denne issues lenger relevant.
