### ISSUE TITLE
Write wiki page for Fhi.HelseId.Web

### ISSUE THREAD

**Issue by OsirisTerje** [FHIDev/Fhi.HelseId#511]
- [ ] Write overview of what this is, and intended use
- [x] Describe how to add this to a Web project.  
- Use code examples.  
- Describe the minimum configurations
- Start with only web client without any Api calls
- [ ] Describe how to expand the code to cover call to an external Api requiring an access tok
- Describe the extra configuration needed
- [ ] Describe the 
- [ ] (Later)  Describe how to add HPR access.
- [ ] Describe other details about the component
- [x] Add links to relevant other pages, including demo and selvbetjening

See [wiki page here](https://github.com/FHIDev/fhi.helseid/wiki/SetupWebBackend)

**Comment by GeirMG** [comment]
Outdated: https://github.com/FHIDev/Fhi.Fellesteam/wiki/api_accesstoken (Information from before the split)
