### ISSUE TITLE
Create Readme.md files for Fhi.HelseId packages

### ISSUE THREAD

**Issue by OsirisTerje** [FHIDev/Fhi.HelseId#515]
Each package should have its own readme file.
It should point to the relevant nuget location, github location and point to the wiki page.
It should state the license and other documents following the repo, including how to contribute
It should have badges for lates version and download numbers.
It may have code examples, even if these also would be present in the wiki pages.

The readme files should be included in the respective packages. 

- [ ] Fhi.HelseId.Web
- [ ] Fhi.HelseId.Api
- [ ] Fhi.HelseId.AuthController
- [ ] Fhi.ClientCredentials
- [ ] Fhi.HelseId.Refit
- [ ] Fhi.ClientCredentials.Refit
- [ ] Fhi.HelseId.Blazor

**Comment by GeirMG** [comment]
Partially solved by: https://github.com/FHIDev/Fhi.HelseId/pull/529
