### ISSUE TITLE
Cleanup demo project in repo "Fhi.HelseId.Demo"

### ISSUE THREAD

**Issue by jennyhougen** [FHIDev/Fhi.HelseId#562]
After improvements there are a couple of other things that should be improved:
- [ ] Solution name should be "Fhi.HelseId.Web.Demo"
- [ ] Remove Weather specs (angular tests)
- [ ] Look into why nuget.config is in Angular client https://github.com/FHIDev/fhi.helseid.demo/blob/main/AngularBFF/Angular.Client/nuget.config
- [ ] Remove NuGet vulnerabilities
- [ ] Turn on "treat warning as errors", see [HelseId ](https://github.com/FHIDev/Fhi.HelseId/blob/master/Directory.Build.props) for example

**Comment by GeirMG** [comment]
Etter å ha tatt en `git clean -xfd` på main får jeg denne:
You seem to not be depending on "@angular/core". This is an error.
C:\Users\ggjul\.nuget\packages\microsoft.visualstudio.javascript.sdk\1.0.784122\Sdk\Sdk.targets(175,5): error MSB3073: The command "npm run build" exited with code 2.
Done building project "Angular.Client.esproj" -- FAILED.

**Comment by GeirMG** [comment]
For å løse "You seem to not be depending on "@angular/core". This is an error." måtte jeg slette "node_modules".

**Comment by GeirMG** [comment]
"mywebapp.client" bør renames til "Angular.Client":

![Image](https://github.com/user-attachments/assets/5205b246-59c3-471d-a792-fe8de013f9ff)

**Comment by GeirMG** [comment]
Hvis man prøver å logge inn med en person som ikke har tilgang får man feil:

![Image](https://github.com/user-attachments/assets/25427dd2-549a-40c6-83dc-ed0411feba4c)
