### ISSUE TITLE
Fhi.HelseId: Avhengigheter til AspNetCore.DataProtection.SQLServer og System.Data.SQLClient for å understøtte lastbalansering 

### ISSUE THREAD

**Issue by verzada** [FHIDev/fhi.helseid#62]
Etter det jeg har forstått fra Rune Grimstad, brukes disse bibliotekene for å understøtte lastbalanseringer.
Burde ikke evt. en slik funksjonalitet ligget i et extensionbibliotek?

**Comment by OsirisTerje** [comment]
Godt poeng.  Det bør vi gjøre, på samme måte som Altinn integrasjonen ble gjort nå.

**Comment by OsirisTerje** [comment]
@verzada  Lyst til å legge inn en PR på det ?

**Comment by martinmine** [comment]
Undersøkte det her litt. Årsaken til at vi har disse avhengighetene er for å støtte sikker lagring av cookies til en SQL-database: https://github.com/FHIDev/fhi.helseid/blob/master/Fhi.HelseId/Api/DataProtection/DataProtectionExtensions.cs
Ettersom dette er snakk om svært lite kode tenker jeg nytteverdien av å ha dette i en egen nugetpakke er mindre enn å ha det i Fhi.HelseId-grunnpakka. Det kan være noe som gir mer mening etter vi har adressert https://github.com/FHIDev/fhi.helseid/issues/397
